name: periodic

on:
  # Run once a month
  schedule:
    - cron: '30 16 15 * *'  # 16:30 UTC (9:30 PST) on the 15th of the month

jobs:
  # Check that our current dependencies still work
  dependency-check:
    uses: "./.github/workflows/test.yaml"
